version: '3.8'

services:
  # บริการเว็บแอปพลิเคชัน Flask
  web:
    build: .
    container_name: ropa_web_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    # ให้รอจนกว่า db จะพร้อมทำงาน ค่อยเปิดตัวเว็บ
    depends_on:
      - db
    networks:
      - ropa_network

volumes:
  mysql_data: # เก็บข้อมูล MySQL ไว้ในเครื่อง ไม่ให้หายเวลาปิด container

networks:
  ropa_network: # วงเน็ตเวิร์กจำลองให้ตู้คุยกันเองได้
